# Generated by Django 5.0.1 on 2024-02-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_delete_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
