# Generated by Django 5.0.1 on 2024-02-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='user_attribute',
            field=models.CharField(choices=[('first_name', 'First Name'), ('last_name', 'Last Name'), ('email', 'Email')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
