# Generated by Django 5.0.1 on 2024-02-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userregistration_user_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='user_attribute',
        ),
    ]
