# Generated by Django 5.0.1 on 2024-02-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_userregistration_user_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
