# Generated by Django 5.0.1 on 2024-02-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userregistration_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistration',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelTable(
            name='userregistration',
            table='app_userregistration',
        ),
    ]
