# Generated by Django 5.0.1 on 2024-02-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userregistration_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
