# Generated by Django 5.0.1 on 2024-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='userregistration',
            table='app_userregistration',
        ),
    ]
