# Generated by Django 5.0.1 on 2024-02-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_userregistration_managers_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissionsgranted to each of their groups.', related_name='%(class)s_user_groups', related_query_name='%(class)s_user_group', to='auth.group', verbose_name='groups'),
        ),
    ]
