# Generated by Django 5.0.1 on 2024-02-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_userregistration_plain_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='plain_password',
        ),
    ]
