# Generated by Django 5.0.1 on 2024-03-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
