# Generated by Django 5.0.1 on 2024-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('receipt', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('payment_for', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
